site_name: VectorCanoe
site_url: ""
use_directory_urls: false
docs_dir: ./docs
copyright: (&copy;) Valeo

nav:
  - Home: 'index.md'
  - Tutorial: 'tutorial.md'
  - Reference: 'reference.md'
  - About: 'about.md'

plugins:
  - mkdocstrings

theme:
  name: readthedocs
  navigation_depth: 1
  locale: en
  nav_style: dark
  hljs_languages:
    - python

